/*
 * INS Gestion V5
 * Il s'agit de l'API v5 de gestion - INS  __Apprenant :__ une personne qui a au moins une inscription validée dans Pegase.  __Inscription :__ se définit par une cible sur une période de mise en œuvre pour un apprenant. Une inscription peut prendre deux états : soit validée, soit annulée.  __Actualisation :__ permet de modifier les données liées à l’apprenant ou à l’inscription alors que la piste a déjà été payée ou validée.   __Gestion des erreurs :__   __200, 201 :__ opération effectuée   __400 :__ erreur de données sur les formats   __403 :__ accès refusé   __404 :__ contenu introuvable   __409 :__ donnée déjà existante   __500 :__ erreur serveur  # Changement majeur/cassant par rapport à V4  1. Suppression de `Inscription.noCandidat`.  1. Ajout de `VoeuBase.noCandidat` et `InscriptionComplete.noCandidat`.  1. Ajout de `VoeuBase.choisi`. 
 *
 * The version of the OpenAPI document: 24.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.esupportail.referentiel.pcscol.ins.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Objects;
import java.util.StringJoiner;

import org.esupportail.referentiel.pcscol.invoker.ApiClient;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
/**
 * Une pièce fournie avec les informations relatives à la demande
 */
@JsonPropertyOrder({
  PieceComplete.JSON_PROPERTY_STATUT,
  PieceComplete.JSON_PROPERTY_MOTIF_DU_REJET,
  PieceComplete.JSON_PROPERTY_CONTENU,
  PieceComplete.JSON_PROPERTY_CONTENU_REFERENCE,
  PieceComplete.JSON_PROPERTY_TYPE_CONTENU,
  PieceComplete.JSON_PROPERTY_DEMANDE_DE_PIECE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-23T10:43:17.979817+02:00[Europe/Paris]", comments = "Generator version: 7.7.0")
public class PieceComplete {
  public static final String JSON_PROPERTY_STATUT = "statut";
  private StatutPiece statut;

  public static final String JSON_PROPERTY_MOTIF_DU_REJET = "motifDuRejet";
  private String motifDuRejet;

  public static final String JSON_PROPERTY_CONTENU = "contenu";
  private byte[] contenu;

  public static final String JSON_PROPERTY_CONTENU_REFERENCE = "contenuReference";
  private String contenuReference;

  public static final String JSON_PROPERTY_TYPE_CONTENU = "typeContenu";
  private String typeContenu;

  public static final String JSON_PROPERTY_DEMANDE_DE_PIECE = "demandeDePiece";
  private DemandeDePiece demandeDePiece;

  public PieceComplete() { 
  }

  public PieceComplete statut(StatutPiece statut) {
    this.statut = statut;
    return this;
  }

  /**
   * Get statut
   * @return statut
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatutPiece getStatut() {
    return statut;
  }


  @JsonProperty(JSON_PROPERTY_STATUT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatut(StatutPiece statut) {
    this.statut = statut;
  }


  public PieceComplete motifDuRejet(String motifDuRejet) {
    this.motifDuRejet = motifDuRejet;
    return this;
  }

  /**
   * le motif de rejet de la pièce
   * @return motifDuRejet
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MOTIF_DU_REJET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMotifDuRejet() {
    return motifDuRejet;
  }


  @JsonProperty(JSON_PROPERTY_MOTIF_DU_REJET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMotifDuRejet(String motifDuRejet) {
    this.motifDuRejet = motifDuRejet;
  }


  public PieceComplete contenu(byte[] contenu) {
    this.contenu = contenu;
    return this;
  }

  /**
   * le contenu de la piece
   * @return contenu
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTENU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public byte[] getContenu() {
    return contenu;
  }


  @JsonProperty(JSON_PROPERTY_CONTENU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContenu(byte[] contenu) {
    this.contenu = contenu;
  }


  public PieceComplete contenuReference(String contenuReference) {
    this.contenuReference = contenuReference;
    return this;
  }

  /**
   * référence au contenu dans le système de stockage Pegase
   * @return contenuReference
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTENU_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getContenuReference() {
    return contenuReference;
  }


  @JsonProperty(JSON_PROPERTY_CONTENU_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContenuReference(String contenuReference) {
    this.contenuReference = contenuReference;
  }


  public PieceComplete typeContenu(String typeContenu) {
    this.typeContenu = typeContenu;
    return this;
  }

  /**
   * le type du contenu
   * @return typeContenu
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE_CONTENU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTypeContenu() {
    return typeContenu;
  }


  @JsonProperty(JSON_PROPERTY_TYPE_CONTENU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTypeContenu(String typeContenu) {
    this.typeContenu = typeContenu;
  }


  public PieceComplete demandeDePiece(DemandeDePiece demandeDePiece) {
    this.demandeDePiece = demandeDePiece;
    return this;
  }

  /**
   * Get demandeDePiece
   * @return demandeDePiece
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DEMANDE_DE_PIECE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public DemandeDePiece getDemandeDePiece() {
    return demandeDePiece;
  }


  @JsonProperty(JSON_PROPERTY_DEMANDE_DE_PIECE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDemandeDePiece(DemandeDePiece demandeDePiece) {
    this.demandeDePiece = demandeDePiece;
  }


  /**
   * Return true if this PieceComplete object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PieceComplete pieceComplete = (PieceComplete) o;
    return Objects.equals(this.statut, pieceComplete.statut) &&
        Objects.equals(this.motifDuRejet, pieceComplete.motifDuRejet) &&
        Arrays.equals(this.contenu, pieceComplete.contenu) &&
        Objects.equals(this.contenuReference, pieceComplete.contenuReference) &&
        Objects.equals(this.typeContenu, pieceComplete.typeContenu) &&
        Objects.equals(this.demandeDePiece, pieceComplete.demandeDePiece);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statut, motifDuRejet, Arrays.hashCode(contenu), contenuReference, typeContenu, demandeDePiece);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PieceComplete {\n");
    sb.append("    statut: ").append(toIndentedString(statut)).append("\n");
    sb.append("    motifDuRejet: ").append(toIndentedString(motifDuRejet)).append("\n");
    sb.append("    contenu: ").append(toIndentedString(contenu)).append("\n");
    sb.append("    contenuReference: ").append(toIndentedString(contenuReference)).append("\n");
    sb.append("    typeContenu: ").append(toIndentedString(typeContenu)).append("\n");
    sb.append("    demandeDePiece: ").append(toIndentedString(demandeDePiece)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `statut` to the URL query string
    if (getStatut() != null) {
      joiner.add(String.format("%sstatut%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getStatut()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `motifDuRejet` to the URL query string
    if (getMotifDuRejet() != null) {
      joiner.add(String.format("%smotifDuRejet%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMotifDuRejet()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `contenu` to the URL query string
    if (getContenu() != null) {
      joiner.add(String.format("%scontenu%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getContenu()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `contenuReference` to the URL query string
    if (getContenuReference() != null) {
      joiner.add(String.format("%scontenuReference%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getContenuReference()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `typeContenu` to the URL query string
    if (getTypeContenu() != null) {
      joiner.add(String.format("%stypeContenu%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTypeContenu()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `demandeDePiece` to the URL query string
    if (getDemandeDePiece() != null) {
      joiner.add(getDemandeDePiece().toUrlQueryString(prefix + "demandeDePiece" + suffix));
    }

    return joiner.toString();
  }
}

