/*
 * INS Gestion V5
 * Il s'agit de l'API v5 de gestion - INS  __Apprenant :__ une personne qui a au moins une inscription validée dans Pegase.  __Inscription :__ se définit par une cible sur une période de mise en œuvre pour un apprenant. Une inscription peut prendre deux états : soit validée, soit annulée.  __Actualisation :__ permet de modifier les données liées à l’apprenant ou à l’inscription alors que la piste a déjà été payée ou validée.   __Gestion des erreurs :__   __200, 201 :__ opération effectuée   __400 :__ erreur de données sur les formats   __403 :__ accès refusé   __404 :__ contenu introuvable   __409 :__ donnée déjà existante   __500 :__ erreur serveur  # Changement majeur/cassant par rapport à V4  1. Suppression de `Inscription.noCandidat`.  1. Ajout de `VoeuBase.noCandidat` et `InscriptionComplete.noCandidat`.  1. Ajout de `VoeuBase.choisi`. 
 *
 * The version of the OpenAPI document: 24.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.esupportail.referentiel.pcscol.ins.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.StringJoiner;

import org.esupportail.referentiel.pcscol.invoker.ApiClient;
import org.esupportail.referentiel.pcscol.invoker.JSON;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
/**
 * Représentation basique d&#39;un voeu
 */
@JsonPropertyOrder({
  VoeuBase.JSON_PROPERTY_EST1,
  VoeuBase.JSON_PROPERTY_NO_CANDIDAT,
  VoeuBase.JSON_PROPERTY_CHOISI,
  VoeuBase.JSON_PROPERTY_ORIGINE,
  VoeuBase.JSON_PROPERTY_STATUT_INSCRIPTION,
  VoeuBase.JSON_PROPERTY_STATUT_PAIEMENT,
  VoeuBase.JSON_PROPERTY_STATUT_PIECES,
  VoeuBase.JSON_PROPERTY_CODE_REGIME_INSCRIPTION,
  VoeuBase.JSON_PROPERTY_BOURSES_ET_AIDES,
  VoeuBase.JSON_PROPERTY_MOTIF_ANNULATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-23T10:43:17.979817+02:00[Europe/Paris]", comments = "Generator version: 7.7.0")
@JsonIgnoreProperties(
  value = "est1", // ignore manually set est1, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the est1 to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "est1", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = Voeu.class, name = "Voeu"),
  @JsonSubTypes.Type(value = VoeuInscription.class, name = "VoeuInscription"),
})

public class VoeuBase {
  public static final String JSON_PROPERTY_EST1 = "est1";
  private String est1;

  public static final String JSON_PROPERTY_NO_CANDIDAT = "noCandidat";
  private String noCandidat;

  public static final String JSON_PROPERTY_CHOISI = "choisi";
  private Boolean choisi;

  public static final String JSON_PROPERTY_ORIGINE = "origine";
  private Origine origine;

  public static final String JSON_PROPERTY_STATUT_INSCRIPTION = "statutInscription";
  private StatutInscriptionVoeu statutInscription;

  public static final String JSON_PROPERTY_STATUT_PAIEMENT = "statutPaiement";
  private StatutPaiementVoeu statutPaiement;

  public static final String JSON_PROPERTY_STATUT_PIECES = "statutPieces";
  private StatutPiecesVoeu statutPieces;

  public static final String JSON_PROPERTY_CODE_REGIME_INSCRIPTION = "codeRegimeInscription";
  private String codeRegimeInscription;

  public static final String JSON_PROPERTY_BOURSES_ET_AIDES = "boursesEtAides";
  private List<String> boursesEtAides = new ArrayList<>();

  public static final String JSON_PROPERTY_MOTIF_ANNULATION = "motifAnnulation";
  private MotifAnnulation motifAnnulation;

  public VoeuBase() { 
  }

  public VoeuBase est1(String est1) {
    this.est1 = est1;
    return this;
  }

  /**
   * Get est1
   * @return est1
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EST1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEst1() {
    return est1;
  }


  @JsonProperty(JSON_PROPERTY_EST1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEst1(String est1) {
    this.est1 = est1;
  }


  public VoeuBase noCandidat(String noCandidat) {
    this.noCandidat = noCandidat;
    return this;
  }

  /**
   * Le numéro de candidature
   * @return noCandidat
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NO_CANDIDAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNoCandidat() {
    return noCandidat;
  }


  @JsonProperty(JSON_PROPERTY_NO_CANDIDAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoCandidat(String noCandidat) {
    this.noCandidat = noCandidat;
  }


  public VoeuBase choisi(Boolean choisi) {
    this.choisi = choisi;
    return this;
  }

  /**
   * Le témoin indique si le voeu fait partie du choix de l&#39;apprenant
   * @return choisi
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHOISI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getChoisi() {
    return choisi;
  }


  @JsonProperty(JSON_PROPERTY_CHOISI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChoisi(Boolean choisi) {
    this.choisi = choisi;
  }


  public VoeuBase origine(Origine origine) {
    this.origine = origine;
    return this;
  }

  /**
   * Get origine
   * @return origine
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORIGINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Origine getOrigine() {
    return origine;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrigine(Origine origine) {
    this.origine = origine;
  }


  public VoeuBase statutInscription(StatutInscriptionVoeu statutInscription) {
    this.statutInscription = statutInscription;
    return this;
  }

  /**
   * Get statutInscription
   * @return statutInscription
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUT_INSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatutInscriptionVoeu getStatutInscription() {
    return statutInscription;
  }


  @JsonProperty(JSON_PROPERTY_STATUT_INSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatutInscription(StatutInscriptionVoeu statutInscription) {
    this.statutInscription = statutInscription;
  }


  public VoeuBase statutPaiement(StatutPaiementVoeu statutPaiement) {
    this.statutPaiement = statutPaiement;
    return this;
  }

  /**
   * Get statutPaiement
   * @return statutPaiement
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUT_PAIEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatutPaiementVoeu getStatutPaiement() {
    return statutPaiement;
  }


  @JsonProperty(JSON_PROPERTY_STATUT_PAIEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatutPaiement(StatutPaiementVoeu statutPaiement) {
    this.statutPaiement = statutPaiement;
  }


  public VoeuBase statutPieces(StatutPiecesVoeu statutPieces) {
    this.statutPieces = statutPieces;
    return this;
  }

  /**
   * Get statutPieces
   * @return statutPieces
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUT_PIECES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatutPiecesVoeu getStatutPieces() {
    return statutPieces;
  }


  @JsonProperty(JSON_PROPERTY_STATUT_PIECES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatutPieces(StatutPiecesVoeu statutPieces) {
    this.statutPieces = statutPieces;
  }


  public VoeuBase codeRegimeInscription(String codeRegimeInscription) {
    this.codeRegimeInscription = codeRegimeInscription;
    return this;
  }

  /**
   * Le code du régime d&#39;inscription
   * @return codeRegimeInscription
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE_REGIME_INSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCodeRegimeInscription() {
    return codeRegimeInscription;
  }


  @JsonProperty(JSON_PROPERTY_CODE_REGIME_INSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodeRegimeInscription(String codeRegimeInscription) {
    this.codeRegimeInscription = codeRegimeInscription;
  }


  public VoeuBase boursesEtAides(List<String> boursesEtAides) {
    this.boursesEtAides = boursesEtAides;
    return this;
  }

  public VoeuBase addBoursesEtAidesItem(String boursesEtAidesItem) {
    if (this.boursesEtAides == null) {
      this.boursesEtAides = new ArrayList<>();
    }
    this.boursesEtAides.add(boursesEtAidesItem);
    return this;
  }

  /**
   * Les bourses et aides financières
   * @return boursesEtAides
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BOURSES_ET_AIDES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getBoursesEtAides() {
    return boursesEtAides;
  }


  @JsonProperty(JSON_PROPERTY_BOURSES_ET_AIDES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBoursesEtAides(List<String> boursesEtAides) {
    this.boursesEtAides = boursesEtAides;
  }


  public VoeuBase motifAnnulation(MotifAnnulation motifAnnulation) {
    this.motifAnnulation = motifAnnulation;
    return this;
  }

  /**
   * Get motifAnnulation
   * @return motifAnnulation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MOTIF_ANNULATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MotifAnnulation getMotifAnnulation() {
    return motifAnnulation;
  }


  @JsonProperty(JSON_PROPERTY_MOTIF_ANNULATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMotifAnnulation(MotifAnnulation motifAnnulation) {
    this.motifAnnulation = motifAnnulation;
  }


  /**
   * Return true if this VoeuBase object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoeuBase voeuBase = (VoeuBase) o;
    return Objects.equals(this.est1, voeuBase.est1) &&
        Objects.equals(this.noCandidat, voeuBase.noCandidat) &&
        Objects.equals(this.choisi, voeuBase.choisi) &&
        Objects.equals(this.origine, voeuBase.origine) &&
        Objects.equals(this.statutInscription, voeuBase.statutInscription) &&
        Objects.equals(this.statutPaiement, voeuBase.statutPaiement) &&
        Objects.equals(this.statutPieces, voeuBase.statutPieces) &&
        Objects.equals(this.codeRegimeInscription, voeuBase.codeRegimeInscription) &&
        Objects.equals(this.boursesEtAides, voeuBase.boursesEtAides) &&
        Objects.equals(this.motifAnnulation, voeuBase.motifAnnulation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(est1, noCandidat, choisi, origine, statutInscription, statutPaiement, statutPieces, codeRegimeInscription, boursesEtAides, motifAnnulation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoeuBase {\n");
    sb.append("    est1: ").append(toIndentedString(est1)).append("\n");
    sb.append("    noCandidat: ").append(toIndentedString(noCandidat)).append("\n");
    sb.append("    choisi: ").append(toIndentedString(choisi)).append("\n");
    sb.append("    origine: ").append(toIndentedString(origine)).append("\n");
    sb.append("    statutInscription: ").append(toIndentedString(statutInscription)).append("\n");
    sb.append("    statutPaiement: ").append(toIndentedString(statutPaiement)).append("\n");
    sb.append("    statutPieces: ").append(toIndentedString(statutPieces)).append("\n");
    sb.append("    codeRegimeInscription: ").append(toIndentedString(codeRegimeInscription)).append("\n");
    sb.append("    boursesEtAides: ").append(toIndentedString(boursesEtAides)).append("\n");
    sb.append("    motifAnnulation: ").append(toIndentedString(motifAnnulation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `est1` to the URL query string
    if (getEst1() != null) {
      joiner.add(String.format("%sest1%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getEst1()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `noCandidat` to the URL query string
    if (getNoCandidat() != null) {
      joiner.add(String.format("%snoCandidat%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getNoCandidat()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `choisi` to the URL query string
    if (getChoisi() != null) {
      joiner.add(String.format("%schoisi%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getChoisi()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `origine` to the URL query string
    if (getOrigine() != null) {
      joiner.add(String.format("%sorigine%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getOrigine()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `statutInscription` to the URL query string
    if (getStatutInscription() != null) {
      joiner.add(String.format("%sstatutInscription%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getStatutInscription()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `statutPaiement` to the URL query string
    if (getStatutPaiement() != null) {
      joiner.add(String.format("%sstatutPaiement%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getStatutPaiement()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `statutPieces` to the URL query string
    if (getStatutPieces() != null) {
      joiner.add(String.format("%sstatutPieces%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getStatutPieces()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `codeRegimeInscription` to the URL query string
    if (getCodeRegimeInscription() != null) {
      joiner.add(String.format("%scodeRegimeInscription%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCodeRegimeInscription()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `boursesEtAides` to the URL query string
    if (getBoursesEtAides() != null) {
      for (int i = 0; i < getBoursesEtAides().size(); i++) {
        joiner.add(String.format("%sboursesEtAides%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(ApiClient.valueToString(getBoursesEtAides().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    // add `motifAnnulation` to the URL query string
    if (getMotifAnnulation() != null) {
      joiner.add(String.format("%smotifAnnulation%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMotifAnnulation()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("Voeu", Voeu.class);
  mappings.put("VoeuInscription", VoeuInscription.class);
  mappings.put("VoeuBase", VoeuBase.class);
  JSON.registerDiscriminator(VoeuBase.class, "est1", mappings);
}
}

