/*
 * API INS V1
 *  # Introduction  Liste l'ensemble des services et des opérations disponibles dans le module INS  Description service INS  # Gestion des erreurs  ## StatusCode  | Code    | Description                                | |---------|--------------------------------------------| | 200     | Opération effectuée                        | |         | Cas particulier: Dans le cas d'APIs de     | |         | type bulk, un 200 peut aussi être retourné | |         | si des données de la requête sont          | |         | considérées en erreur                      | | 201     | Ressource créée                            | | 400     | Données envoyées par le client invalides   | | 403     | Accès refusé                               | | 404     | Ressource inexistante                      | | 409     | donnée déjà existante                      | | 500     | Erreur technique rencontrée par le serveur |   ## Codes d'erreurs  | Code      | Description                                | |-----------|--------------------------------------------| | notNull   | la propriété est obligatoire               | | notBlank  | la propriété ne doit pas être vide         | | size      | la longueur de la propriété est invalide   | | pattern   | les caractères ou la syntaxe de            | |           | la propriété est invalide                  | | genre     | le genre de la personne est invalide       | | dateEntre | la date est invalide                       | | telephone | le téléphone est invalide                  | | email     | le mail est invalide                       | 
 *
 * The version of the OpenAPI document: 1.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.esupportail.referentiel.pcscol.insv115.model;

import java.util.Objects;
import java.util.StringJoiner;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
/**
 * InscriptionApprenantPeriodeEtChemin
 */
@JsonPropertyOrder({
  InscriptionApprenantPeriodeEtChemin.JSON_PROPERTY_INSCRIPTION,
  InscriptionApprenantPeriodeEtChemin.JSON_PROPERTY_APPRENANT,
  InscriptionApprenantPeriodeEtChemin.JSON_PROPERTY_PERIODE,
  InscriptionApprenantPeriodeEtChemin.JSON_PROPERTY_CHEMIN,
  InscriptionApprenantPeriodeEtChemin.JSON_PROPERTY_PAIEMENT_AVEC_STATUT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-09T10:27:39.429576628+02:00[Europe/Paris]", comments = "Generator version: 7.15.0")
public class InscriptionApprenantPeriodeEtChemin {
  public static final String JSON_PROPERTY_INSCRIPTION = "inscription";
  @jakarta.annotation.Nonnull
  private Inscription inscription;

  public static final String JSON_PROPERTY_APPRENANT = "apprenant";
  @jakarta.annotation.Nonnull
  private Apprenant apprenant;

  public static final String JSON_PROPERTY_PERIODE = "periode";
  @jakarta.annotation.Nonnull
  private Periode periode;

  public static final String JSON_PROPERTY_CHEMIN = "chemin";
  @jakarta.annotation.Nonnull
  private Chemin chemin;

  public static final String JSON_PROPERTY_PAIEMENT_AVEC_STATUT = "paiementAvecStatut";
  @jakarta.annotation.Nullable
  private PaiementAvecStatut paiementAvecStatut;

  public InscriptionApprenantPeriodeEtChemin() { 
  }

  public InscriptionApprenantPeriodeEtChemin inscription(@jakarta.annotation.Nonnull Inscription inscription) {
    this.inscription = inscription;
    return this;
  }

  /**
   * Get inscription
   * @return inscription
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Inscription getInscription() {
    return inscription;
  }


  @JsonProperty(JSON_PROPERTY_INSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInscription(@jakarta.annotation.Nonnull Inscription inscription) {
    this.inscription = inscription;
  }


  public InscriptionApprenantPeriodeEtChemin apprenant(@jakarta.annotation.Nonnull Apprenant apprenant) {
    this.apprenant = apprenant;
    return this;
  }

  /**
   * Get apprenant
   * @return apprenant
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_APPRENANT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Apprenant getApprenant() {
    return apprenant;
  }


  @JsonProperty(JSON_PROPERTY_APPRENANT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setApprenant(@jakarta.annotation.Nonnull Apprenant apprenant) {
    this.apprenant = apprenant;
  }


  public InscriptionApprenantPeriodeEtChemin periode(@jakarta.annotation.Nonnull Periode periode) {
    this.periode = periode;
    return this;
  }

  /**
   * Get periode
   * @return periode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PERIODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Periode getPeriode() {
    return periode;
  }


  @JsonProperty(JSON_PROPERTY_PERIODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPeriode(@jakarta.annotation.Nonnull Periode periode) {
    this.periode = periode;
  }


  public InscriptionApprenantPeriodeEtChemin chemin(@jakarta.annotation.Nonnull Chemin chemin) {
    this.chemin = chemin;
    return this;
  }

  /**
   * Get chemin
   * @return chemin
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CHEMIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Chemin getChemin() {
    return chemin;
  }


  @JsonProperty(JSON_PROPERTY_CHEMIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChemin(@jakarta.annotation.Nonnull Chemin chemin) {
    this.chemin = chemin;
  }


  public InscriptionApprenantPeriodeEtChemin paiementAvecStatut(@jakarta.annotation.Nullable PaiementAvecStatut paiementAvecStatut) {
    this.paiementAvecStatut = paiementAvecStatut;
    return this;
  }

  /**
   * Get paiementAvecStatut
   * @return paiementAvecStatut
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAIEMENT_AVEC_STATUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PaiementAvecStatut getPaiementAvecStatut() {
    return paiementAvecStatut;
  }


  @JsonProperty(JSON_PROPERTY_PAIEMENT_AVEC_STATUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaiementAvecStatut(@jakarta.annotation.Nullable PaiementAvecStatut paiementAvecStatut) {
    this.paiementAvecStatut = paiementAvecStatut;
  }


  /**
   * Return true if this InscriptionApprenantPeriodeEtChemin object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InscriptionApprenantPeriodeEtChemin inscriptionApprenantPeriodeEtChemin = (InscriptionApprenantPeriodeEtChemin) o;
    return Objects.equals(this.inscription, inscriptionApprenantPeriodeEtChemin.inscription) &&
        Objects.equals(this.apprenant, inscriptionApprenantPeriodeEtChemin.apprenant) &&
        Objects.equals(this.periode, inscriptionApprenantPeriodeEtChemin.periode) &&
        Objects.equals(this.chemin, inscriptionApprenantPeriodeEtChemin.chemin) &&
        Objects.equals(this.paiementAvecStatut, inscriptionApprenantPeriodeEtChemin.paiementAvecStatut);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inscription, apprenant, periode, chemin, paiementAvecStatut);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InscriptionApprenantPeriodeEtChemin {\n");
    sb.append("    inscription: ").append(toIndentedString(inscription)).append("\n");
    sb.append("    apprenant: ").append(toIndentedString(apprenant)).append("\n");
    sb.append("    periode: ").append(toIndentedString(periode)).append("\n");
    sb.append("    chemin: ").append(toIndentedString(chemin)).append("\n");
    sb.append("    paiementAvecStatut: ").append(toIndentedString(paiementAvecStatut)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `inscription` to the URL query string
    if (getInscription() != null) {
      joiner.add(getInscription().toUrlQueryString(prefix + "inscription" + suffix));
    }

    // add `apprenant` to the URL query string
    if (getApprenant() != null) {
      joiner.add(getApprenant().toUrlQueryString(prefix + "apprenant" + suffix));
    }

    // add `periode` to the URL query string
    if (getPeriode() != null) {
      joiner.add(getPeriode().toUrlQueryString(prefix + "periode" + suffix));
    }

    // add `chemin` to the URL query string
    if (getChemin() != null) {
      joiner.add(getChemin().toUrlQueryString(prefix + "chemin" + suffix));
    }

    // add `paiementAvecStatut` to the URL query string
    if (getPaiementAvecStatut() != null) {
      joiner.add(getPaiementAvecStatut().toUrlQueryString(prefix + "paiementAvecStatut" + suffix));
    }

    return joiner.toString();
  }
}

