/*
 * API INS V1
 *  # Introduction  Liste l'ensemble des services et des opérations disponibles dans le module INS  Description service INS  # Gestion des erreurs  ## StatusCode  | Code    | Description                                | |---------|--------------------------------------------| | 200     | Opération effectuée                        | |         | Cas particulier: Dans le cas d'APIs de     | |         | type bulk, un 200 peut aussi être retourné | |         | si des données de la requête sont          | |         | considérées en erreur                      | | 201     | Ressource créée                            | | 400     | Données envoyées par le client invalides   | | 403     | Accès refusé                               | | 404     | Ressource inexistante                      | | 409     | donnée déjà existante                      | | 500     | Erreur technique rencontrée par le serveur |   ## Codes d'erreurs  | Code      | Description                                | |-----------|--------------------------------------------| | notNull   | la propriété est obligatoire               | | notBlank  | la propriété ne doit pas être vide         | | size      | la longueur de la propriété est invalide   | | pattern   | les caractères ou la syntaxe de            | |           | la propriété est invalide                  | | genre     | le genre de la personne est invalide       | | dateEntre | la date est invalide                       | | telephone | le téléphone est invalide                  | | email     | le mail est invalide                       | 
 *
 * The version of the OpenAPI document: 1.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.esupportail.referentiel.pcscol.insv115.model;

import java.util.Objects;
import java.util.StringJoiner;

import org.esupportail.referentiel.pcscol.invoker.ApiClient;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
/**
 * ItemError
 */
@JsonPropertyOrder({
  ItemError.JSON_PROPERTY_CODE,
  ItemError.JSON_PROPERTY_MESSAGE,
  ItemError.JSON_PROPERTY_CHAMP,
  ItemError.JSON_PROPERTY_MESSAGE_DETAILS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-09T10:27:39.429576628+02:00[Europe/Paris]", comments = "Generator version: 7.15.0")
public class ItemError {
  public static final String JSON_PROPERTY_CODE = "code";
  @jakarta.annotation.Nonnull
  private String code;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nonnull
  private String message;

  public static final String JSON_PROPERTY_CHAMP = "champ";
  @jakarta.annotation.Nullable
  private String champ;

  public static final String JSON_PROPERTY_MESSAGE_DETAILS = "messageDetails";
  @jakarta.annotation.Nullable
  private ItemErrorMessageDetails messageDetails;

  public ItemError() { 
  }

  public ItemError code(@jakarta.annotation.Nonnull String code) {
    this.code = code;
    return this;
  }

  /**
   * code d&#39;erreur
   * @return code
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(@jakarta.annotation.Nonnull String code) {
    this.code = code;
  }


  public ItemError message(@jakarta.annotation.Nonnull String message) {
    this.message = message;
    return this;
  }

  /**
   * message d&#39;erreur à destination d&#39;un utilisateur final (ou pour logguer)
   * @return message
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@jakarta.annotation.Nonnull String message) {
    this.message = message;
  }


  public ItemError champ(@jakarta.annotation.Nullable String champ) {
    this.champ = champ;
    return this;
  }

  /**
   * Propriété sur laquelle porte l&#39;erreur. null si l&#39;erreur ne porte sur aucune propriété particulière
   * @return champ
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getChamp() {
    return champ;
  }


  @JsonProperty(JSON_PROPERTY_CHAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChamp(@jakarta.annotation.Nullable String champ) {
    this.champ = champ;
  }


  public ItemError messageDetails(@jakarta.annotation.Nullable ItemErrorMessageDetails messageDetails) {
    this.messageDetails = messageDetails;
    return this;
  }

  /**
   * Get messageDetails
   * @return messageDetails
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ItemErrorMessageDetails getMessageDetails() {
    return messageDetails;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessageDetails(@jakarta.annotation.Nullable ItemErrorMessageDetails messageDetails) {
    this.messageDetails = messageDetails;
  }


  /**
   * Return true if this ItemError object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemError itemError = (ItemError) o;
    return Objects.equals(this.code, itemError.code) &&
        Objects.equals(this.message, itemError.message) &&
        Objects.equals(this.champ, itemError.champ) &&
        Objects.equals(this.messageDetails, itemError.messageDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, champ, messageDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemError {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    champ: ").append(toIndentedString(champ)).append("\n");
    sb.append("    messageDetails: ").append(toIndentedString(messageDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `code` to the URL query string
    if (getCode() != null) {
      joiner.add(String.format("%scode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCode()))));
    }

    // add `message` to the URL query string
    if (getMessage() != null) {
      joiner.add(String.format("%smessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessage()))));
    }

    // add `champ` to the URL query string
    if (getChamp() != null) {
      joiner.add(String.format("%schamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChamp()))));
    }

    // add `messageDetails` to the URL query string
    if (getMessageDetails() != null) {
      joiner.add(getMessageDetails().toUrlQueryString(prefix + "messageDetails" + suffix));
    }

    return joiner.toString();
  }
}

