/*
 * MOF Application v1 - Mise en œuvre de l'offre de formation - Bloc «application»
 * Liste l'ensemble des services et des opérations utilisées par l'application front du module MOF (Mise en œuvre de l'offre de formation)  ### Authentification/autorisation obligatoire  Pour tout appel à une opération vous devez être authentifié/authorisé (voir le paragraphe [Authentification](#section/Authentication) pour les détails).  ### Type de données  Sauf indications spécifiques données au niveau de l'opération, les types de données utilisés dans cette API sont les suivants :  * string - Chaîne de caractères encodée en UTF8 (ex : `Une chaîne de caractère`)    * Dans le cas des descripteurs de type `codeXxx`, seuls les caractères de A à Z, de 0 à 9 et le tiret(-) sont autorisés    * Dans le cas des descripteurs de type montant ou nombre avec une partie décimale, seuls les caractères de 0 à 9 et le point(.) sont autorisés (ex : `12525.99`)  * string($date) - Une date sous la forme d'une chaîne de caractères (ex : `2020-02-25`, norme [ISO-8601](https://fr.wikipedia.org/wiki/ISO_8601))  * string($date-time) - Une date et heure avec fuseau horaire sous la forme d'une chaîne de caractères (ex : `2020-02-25T18:36:22+02:00`, norme [ISO-8601](https://fr.wikipedia.org/wiki/ISO_8601))  * integer($int64) - Un entier sur 64 bits (de -9 223 372 036 854 775 808 à 9 223 372 036 854 775 807) (ex : `2542`)  * integer($int32) - Un entier sur 32 bits (de –2 147 483 648 à 2 147 483 647) (ex : `2542`)  * boolean - Un booléen représenté par `true` ou `false`  ### Code retour   * 200 - Ok : L'opération s'est déroulée avec succès  * 201 - Created : L'opération a aboutie à la création d'une ressource  * 400 - Bad request :    * Un ou des paramètres d'entrées sont erronées    * Une erreur fonctionnelle s'est produite  * 404 - Not Found : La ressource demandée n'est pas trouvé    * Remarque : Dans le cas des opérations retournant une liste, on recevra un code 200 avec en résultat une liste vide  * 500 - Internal server error : Erreur inattendue et non gérés 
 *
 * The version of the OpenAPI document: 2.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.esupportail.referentiel.pcscol.model.formation;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.swagger.annotations.ApiModelProperty;


/**
 * Formation
 */
@JsonPropertyOrder({
  Formation.JSON_PROPERTY_CODE,
  Formation.JSON_PROPERTY_VERSION,
  Formation.JSON_PROPERTY_LIBELLE,
  Formation.JSON_PROPERTY_LIBELLE_COURT,
  Formation.JSON_PROPERTY_LIBELLE_LONG,
  Formation.JSON_PROPERTY_TYPE,
  Formation.JSON_PROPERTY_PERIODE,
  Formation.JSON_PROPERTY_STRUCTURE_BUDGETAIRE,
  Formation.JSON_PROPERTY_LISTE_CODE_REGIME_INSCRIPTION,
  Formation.JSON_PROPERTY_NB_INSCRIPTIONS_AUTORISEES,
  Formation.JSON_PROPERTY_LISTE_CODE_BOURSE_ET_AIDE_FINANCIERE,
  Formation.JSON_PROPERTY_OUVERTE_A_INSCRIPTION,
  Formation.JSON_PROPERTY_OUVERTE_AU_CHOIX_DU_CURSUS,
  Formation.JSON_PROPERTY_TITRE_ACCES_NECESSAIRE,
  Formation.JSON_PROPERTY_TELE_ENSEIGNEMENT,
  Formation.JSON_PROPERTY_JAMAIS_OUVERTE_A_INSCRIPTION,
  Formation.JSON_PROPERTY_JAMAIS_OUVERTE_AU_CHOIX_DU_CURSUS,
  Formation.JSON_PROPERTY_ENVOYEE_A_INSCRIPTION,
  Formation.JSON_PROPERTY_LISTE_CALENDRIER,
  Formation.JSON_PROPERTY_ACTUALISER_ADMINISTRATIVEMENT,
  Formation.JSON_PROPERTY_TARIFICATION,
  Formation.JSON_PROPERTY_CODE_TYPE_DIPLOME
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-16T08:54:45.925006+01:00[Europe/Paris]")
public class Formation {
  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  public static final String JSON_PROPERTY_VERSION = "version";
  private Integer version;

  public static final String JSON_PROPERTY_LIBELLE = "libelle";
  private String libelle;

  public static final String JSON_PROPERTY_LIBELLE_COURT = "libelleCourt";
  private String libelleCourt;

  public static final String JSON_PROPERTY_LIBELLE_LONG = "libelleLong";
  private String libelleLong;

  public static final String JSON_PROPERTY_TYPE = "type";
  private ObjetLibelle type;

  public static final String JSON_PROPERTY_PERIODE = "periode";
  private Periode periode;

  public static final String JSON_PROPERTY_STRUCTURE_BUDGETAIRE = "structureBudgetaire";
  private Structure structureBudgetaire;

  public static final String JSON_PROPERTY_LISTE_CODE_REGIME_INSCRIPTION = "listeCodeRegimeInscription";
  private List<String> listeCodeRegimeInscription = null;

  public static final String JSON_PROPERTY_NB_INSCRIPTIONS_AUTORISEES = "nbInscriptionsAutorisees";
  private Integer nbInscriptionsAutorisees;

  public static final String JSON_PROPERTY_LISTE_CODE_BOURSE_ET_AIDE_FINANCIERE = "listeCodeBourseEtAideFinanciere";
  private List<String> listeCodeBourseEtAideFinanciere = null;

  public static final String JSON_PROPERTY_OUVERTE_A_INSCRIPTION = "ouverteAInscription";
  private Boolean ouverteAInscription;

  public static final String JSON_PROPERTY_OUVERTE_AU_CHOIX_DU_CURSUS = "ouverteAuChoixDuCursus";
  private Boolean ouverteAuChoixDuCursus;

  public static final String JSON_PROPERTY_TITRE_ACCES_NECESSAIRE = "titreAccesNecessaire";
  private Boolean titreAccesNecessaire;

  public static final String JSON_PROPERTY_TELE_ENSEIGNEMENT = "teleEnseignement";
  private Boolean teleEnseignement;

  public static final String JSON_PROPERTY_JAMAIS_OUVERTE_A_INSCRIPTION = "jamaisOuverteAInscription";
  private Boolean jamaisOuverteAInscription;

  public static final String JSON_PROPERTY_JAMAIS_OUVERTE_AU_CHOIX_DU_CURSUS = "jamaisOuverteAuChoixDuCursus";
  private Boolean jamaisOuverteAuChoixDuCursus;

  public static final String JSON_PROPERTY_ENVOYEE_A_INSCRIPTION = "envoyeeAInscription";
  private Boolean envoyeeAInscription;

  public static final String JSON_PROPERTY_LISTE_CALENDRIER = "listeCalendrier";
  private List<Calendrier> listeCalendrier = null;

  public static final String JSON_PROPERTY_ACTUALISER_ADMINISTRATIVEMENT = "actualiserAdministrativement";
  private Boolean actualiserAdministrativement;

  public static final String JSON_PROPERTY_TARIFICATION = "tarification";
  private DroitTarification tarification;

  public static final String JSON_PROPERTY_CODE_TYPE_DIPLOME = "codeTypeDiplome";
  private String codeTypeDiplome;

  public Formation() { 
  }

  public Formation code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Le code de la formation
   * @return code
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Le code de la formation")
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(String code) {
    this.code = code;
  }


  public Formation version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * La version de la formation
   * @return version
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "La version de la formation")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(Integer version) {
    this.version = version;
  }


  public Formation libelle(String libelle) {
    this.libelle = libelle;
    return this;
  }

   /**
   * Le libellé de la formation à afficher
   * @return libelle
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Le libellé de la formation à afficher")
  @JsonProperty(JSON_PROPERTY_LIBELLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLibelle() {
    return libelle;
  }


  @JsonProperty(JSON_PROPERTY_LIBELLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLibelle(String libelle) {
    this.libelle = libelle;
  }


  public Formation libelleCourt(String libelleCourt) {
    this.libelleCourt = libelleCourt;
    return this;
  }

   /**
   * Le libellé court de la formation
   * @return libelleCourt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Le libellé court de la formation")
  @JsonProperty(JSON_PROPERTY_LIBELLE_COURT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLibelleCourt() {
    return libelleCourt;
  }


  @JsonProperty(JSON_PROPERTY_LIBELLE_COURT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLibelleCourt(String libelleCourt) {
    this.libelleCourt = libelleCourt;
  }


  public Formation libelleLong(String libelleLong) {
    this.libelleLong = libelleLong;
    return this;
  }

   /**
   * Le libellé long de la formation
   * @return libelleLong
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Le libellé long de la formation")
  @JsonProperty(JSON_PROPERTY_LIBELLE_LONG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLibelleLong() {
    return libelleLong;
  }


  @JsonProperty(JSON_PROPERTY_LIBELLE_LONG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLibelleLong(String libelleLong) {
    this.libelleLong = libelleLong;
  }


  public Formation type(ObjetLibelle type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ObjetLibelle getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(ObjetLibelle type) {
    this.type = type;
  }


  public Formation periode(Periode periode) {
    this.periode = periode;
    return this;
  }

   /**
   * Get periode
   * @return periode
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PERIODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Periode getPeriode() {
    return periode;
  }


  @JsonProperty(JSON_PROPERTY_PERIODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPeriode(Periode periode) {
    this.periode = periode;
  }


  public Formation structureBudgetaire(Structure structureBudgetaire) {
    this.structureBudgetaire = structureBudgetaire;
    return this;
  }

   /**
   * Get structureBudgetaire
   * @return structureBudgetaire
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STRUCTURE_BUDGETAIRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Structure getStructureBudgetaire() {
    return structureBudgetaire;
  }


  @JsonProperty(JSON_PROPERTY_STRUCTURE_BUDGETAIRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStructureBudgetaire(Structure structureBudgetaire) {
    this.structureBudgetaire = structureBudgetaire;
  }


  public Formation listeCodeRegimeInscription(List<String> listeCodeRegimeInscription) {
    this.listeCodeRegimeInscription = listeCodeRegimeInscription;
    return this;
  }

  public Formation addListeCodeRegimeInscriptionItem(String listeCodeRegimeInscriptionItem) {
    if (this.listeCodeRegimeInscription == null) {
      this.listeCodeRegimeInscription = new ArrayList<>();
    }
    this.listeCodeRegimeInscription.add(listeCodeRegimeInscriptionItem);
    return this;
  }

   /**
   * Get listeCodeRegimeInscription
   * @return listeCodeRegimeInscription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LISTE_CODE_REGIME_INSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getListeCodeRegimeInscription() {
    return listeCodeRegimeInscription;
  }


  @JsonProperty(JSON_PROPERTY_LISTE_CODE_REGIME_INSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setListeCodeRegimeInscription(List<String> listeCodeRegimeInscription) {
    this.listeCodeRegimeInscription = listeCodeRegimeInscription;
  }


  public Formation nbInscriptionsAutorisees(Integer nbInscriptionsAutorisees) {
    this.nbInscriptionsAutorisees = nbInscriptionsAutorisees;
    return this;
  }

   /**
   * le nombre d&#39;inscriptions autorisées (correspond au nombre maximum de fois qu&#39;un étudiant peut s&#39;inscrire)
   * @return nbInscriptionsAutorisees
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "le nombre d'inscriptions autorisées (correspond au nombre maximum de fois qu'un étudiant peut s'inscrire)")
  @JsonProperty(JSON_PROPERTY_NB_INSCRIPTIONS_AUTORISEES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNbInscriptionsAutorisees() {
    return nbInscriptionsAutorisees;
  }


  @JsonProperty(JSON_PROPERTY_NB_INSCRIPTIONS_AUTORISEES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNbInscriptionsAutorisees(Integer nbInscriptionsAutorisees) {
    this.nbInscriptionsAutorisees = nbInscriptionsAutorisees;
  }


  public Formation listeCodeBourseEtAideFinanciere(List<String> listeCodeBourseEtAideFinanciere) {
    this.listeCodeBourseEtAideFinanciere = listeCodeBourseEtAideFinanciere;
    return this;
  }

  public Formation addListeCodeBourseEtAideFinanciereItem(String listeCodeBourseEtAideFinanciereItem) {
    if (this.listeCodeBourseEtAideFinanciere == null) {
      this.listeCodeBourseEtAideFinanciere = new ArrayList<>();
    }
    this.listeCodeBourseEtAideFinanciere.add(listeCodeBourseEtAideFinanciereItem);
    return this;
  }

   /**
   * les bourses et aides financières
   * @return listeCodeBourseEtAideFinanciere
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "les bourses et aides financières")
  @JsonProperty(JSON_PROPERTY_LISTE_CODE_BOURSE_ET_AIDE_FINANCIERE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getListeCodeBourseEtAideFinanciere() {
    return listeCodeBourseEtAideFinanciere;
  }


  @JsonProperty(JSON_PROPERTY_LISTE_CODE_BOURSE_ET_AIDE_FINANCIERE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setListeCodeBourseEtAideFinanciere(List<String> listeCodeBourseEtAideFinanciere) {
    this.listeCodeBourseEtAideFinanciere = listeCodeBourseEtAideFinanciere;
  }


  public Formation ouverteAInscription(Boolean ouverteAInscription) {
    this.ouverteAInscription = ouverteAInscription;
    return this;
  }

   /**
   * est-ce que la formation est ouverte à l&#39;inscription ?
   * @return ouverteAInscription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "est-ce que la formation est ouverte à l'inscription ?")
  @JsonProperty(JSON_PROPERTY_OUVERTE_A_INSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOuverteAInscription() {
    return ouverteAInscription;
  }


  @JsonProperty(JSON_PROPERTY_OUVERTE_A_INSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOuverteAInscription(Boolean ouverteAInscription) {
    this.ouverteAInscription = ouverteAInscription;
  }


  public Formation ouverteAuChoixDuCursus(Boolean ouverteAuChoixDuCursus) {
    this.ouverteAuChoixDuCursus = ouverteAuChoixDuCursus;
    return this;
  }

   /**
   * est-ce que la formation est ouverte au choix du cursus ?
   * @return ouverteAuChoixDuCursus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "est-ce que la formation est ouverte au choix du cursus ?")
  @JsonProperty(JSON_PROPERTY_OUVERTE_AU_CHOIX_DU_CURSUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOuverteAuChoixDuCursus() {
    return ouverteAuChoixDuCursus;
  }


  @JsonProperty(JSON_PROPERTY_OUVERTE_AU_CHOIX_DU_CURSUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOuverteAuChoixDuCursus(Boolean ouverteAuChoixDuCursus) {
    this.ouverteAuChoixDuCursus = ouverteAuChoixDuCursus;
  }


  public Formation titreAccesNecessaire(Boolean titreAccesNecessaire) {
    this.titreAccesNecessaire = titreAccesNecessaire;
    return this;
  }

   /**
   * Demander le titre d&#39;accès de l&#39;étudiant lors de l&#39;inscription ?
   * @return titreAccesNecessaire
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Demander le titre d'accès de l'étudiant lors de l'inscription ?")
  @JsonProperty(JSON_PROPERTY_TITRE_ACCES_NECESSAIRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTitreAccesNecessaire() {
    return titreAccesNecessaire;
  }


  @JsonProperty(JSON_PROPERTY_TITRE_ACCES_NECESSAIRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitreAccesNecessaire(Boolean titreAccesNecessaire) {
    this.titreAccesNecessaire = titreAccesNecessaire;
  }


  public Formation teleEnseignement(Boolean teleEnseignement) {
    this.teleEnseignement = teleEnseignement;
    return this;
  }

   /**
   * est-ce une formation en télé-enseignement ?
   * @return teleEnseignement
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "est-ce une formation en télé-enseignement ?")
  @JsonProperty(JSON_PROPERTY_TELE_ENSEIGNEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTeleEnseignement() {
    return teleEnseignement;
  }


  @JsonProperty(JSON_PROPERTY_TELE_ENSEIGNEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTeleEnseignement(Boolean teleEnseignement) {
    this.teleEnseignement = teleEnseignement;
  }


  public Formation jamaisOuverteAInscription(Boolean jamaisOuverteAInscription) {
    this.jamaisOuverteAInscription = jamaisOuverteAInscription;
    return this;
  }

   /**
   * est-ce que la formation a jamais été ouverte à l&#39;inscription ?
   * @return jamaisOuverteAInscription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "est-ce que la formation a jamais été ouverte à l'inscription ?")
  @JsonProperty(JSON_PROPERTY_JAMAIS_OUVERTE_A_INSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getJamaisOuverteAInscription() {
    return jamaisOuverteAInscription;
  }


  @JsonProperty(JSON_PROPERTY_JAMAIS_OUVERTE_A_INSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJamaisOuverteAInscription(Boolean jamaisOuverteAInscription) {
    this.jamaisOuverteAInscription = jamaisOuverteAInscription;
  }


  public Formation jamaisOuverteAuChoixDuCursus(Boolean jamaisOuverteAuChoixDuCursus) {
    this.jamaisOuverteAuChoixDuCursus = jamaisOuverteAuChoixDuCursus;
    return this;
  }

   /**
   * est-ce que la formation a jamais été ouverte au choix du cursus ?
   * @return jamaisOuverteAuChoixDuCursus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "est-ce que la formation a jamais été ouverte au choix du cursus ?")
  @JsonProperty(JSON_PROPERTY_JAMAIS_OUVERTE_AU_CHOIX_DU_CURSUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getJamaisOuverteAuChoixDuCursus() {
    return jamaisOuverteAuChoixDuCursus;
  }


  @JsonProperty(JSON_PROPERTY_JAMAIS_OUVERTE_AU_CHOIX_DU_CURSUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJamaisOuverteAuChoixDuCursus(Boolean jamaisOuverteAuChoixDuCursus) {
    this.jamaisOuverteAuChoixDuCursus = jamaisOuverteAuChoixDuCursus;
  }


  public Formation envoyeeAInscription(Boolean envoyeeAInscription) {
    this.envoyeeAInscription = envoyeeAInscription;
    return this;
  }

   /**
   * est-ce que la formation a été envoyée à l&#39;inscription ?
   * @return envoyeeAInscription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "est-ce que la formation a été envoyée à l'inscription ?")
  @JsonProperty(JSON_PROPERTY_ENVOYEE_A_INSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnvoyeeAInscription() {
    return envoyeeAInscription;
  }


  @JsonProperty(JSON_PROPERTY_ENVOYEE_A_INSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnvoyeeAInscription(Boolean envoyeeAInscription) {
    this.envoyeeAInscription = envoyeeAInscription;
  }


  public Formation listeCalendrier(List<Calendrier> listeCalendrier) {
    this.listeCalendrier = listeCalendrier;
    return this;
  }

  public Formation addListeCalendrierItem(Calendrier listeCalendrierItem) {
    if (this.listeCalendrier == null) {
      this.listeCalendrier = new ArrayList<>();
    }
    this.listeCalendrier.add(listeCalendrierItem);
    return this;
  }

   /**
   * Get listeCalendrier
   * @return listeCalendrier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LISTE_CALENDRIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Calendrier> getListeCalendrier() {
    return listeCalendrier;
  }


  @JsonProperty(JSON_PROPERTY_LISTE_CALENDRIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setListeCalendrier(List<Calendrier> listeCalendrier) {
    this.listeCalendrier = listeCalendrier;
  }


  public Formation actualiserAdministrativement(Boolean actualiserAdministrativement) {
    this.actualiserAdministrativement = actualiserAdministrativement;
    return this;
  }

   /**
   * est-ce que la formation est actualisée administrativement ?
   * @return actualiserAdministrativement
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "est-ce que la formation est actualisée administrativement ?")
  @JsonProperty(JSON_PROPERTY_ACTUALISER_ADMINISTRATIVEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActualiserAdministrativement() {
    return actualiserAdministrativement;
  }


  @JsonProperty(JSON_PROPERTY_ACTUALISER_ADMINISTRATIVEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActualiserAdministrativement(Boolean actualiserAdministrativement) {
    this.actualiserAdministrativement = actualiserAdministrativement;
  }


  public Formation tarification(DroitTarification tarification) {
    this.tarification = tarification;
    return this;
  }

   /**
   * Get tarification
   * @return tarification
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TARIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DroitTarification getTarification() {
    return tarification;
  }


  @JsonProperty(JSON_PROPERTY_TARIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTarification(DroitTarification tarification) {
    this.tarification = tarification;
  }


  public Formation codeTypeDiplome(String codeTypeDiplome) {
    this.codeTypeDiplome = codeTypeDiplome;
    return this;
  }

   /**
   * Le code du type de diplôme
   * @return codeTypeDiplome
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Le code du type de diplôme")
  @JsonProperty(JSON_PROPERTY_CODE_TYPE_DIPLOME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCodeTypeDiplome() {
    return codeTypeDiplome;
  }


  @JsonProperty(JSON_PROPERTY_CODE_TYPE_DIPLOME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodeTypeDiplome(String codeTypeDiplome) {
    this.codeTypeDiplome = codeTypeDiplome;
  }


  /**
   * Return true if this Formation object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Formation formation = (Formation) o;
    return Objects.equals(this.code, formation.code) &&
        Objects.equals(this.version, formation.version) &&
        Objects.equals(this.libelle, formation.libelle) &&
        Objects.equals(this.libelleCourt, formation.libelleCourt) &&
        Objects.equals(this.libelleLong, formation.libelleLong) &&
        Objects.equals(this.type, formation.type) &&
        Objects.equals(this.periode, formation.periode) &&
        Objects.equals(this.structureBudgetaire, formation.structureBudgetaire) &&
        Objects.equals(this.listeCodeRegimeInscription, formation.listeCodeRegimeInscription) &&
        Objects.equals(this.nbInscriptionsAutorisees, formation.nbInscriptionsAutorisees) &&
        Objects.equals(this.listeCodeBourseEtAideFinanciere, formation.listeCodeBourseEtAideFinanciere) &&
        Objects.equals(this.ouverteAInscription, formation.ouverteAInscription) &&
        Objects.equals(this.ouverteAuChoixDuCursus, formation.ouverteAuChoixDuCursus) &&
        Objects.equals(this.titreAccesNecessaire, formation.titreAccesNecessaire) &&
        Objects.equals(this.teleEnseignement, formation.teleEnseignement) &&
        Objects.equals(this.jamaisOuverteAInscription, formation.jamaisOuverteAInscription) &&
        Objects.equals(this.jamaisOuverteAuChoixDuCursus, formation.jamaisOuverteAuChoixDuCursus) &&
        Objects.equals(this.envoyeeAInscription, formation.envoyeeAInscription) &&
        Objects.equals(this.listeCalendrier, formation.listeCalendrier) &&
        Objects.equals(this.actualiserAdministrativement, formation.actualiserAdministrativement) &&
        Objects.equals(this.tarification, formation.tarification) &&
        Objects.equals(this.codeTypeDiplome, formation.codeTypeDiplome);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, version, libelle, libelleCourt, libelleLong, type, periode, structureBudgetaire, listeCodeRegimeInscription, nbInscriptionsAutorisees, listeCodeBourseEtAideFinanciere, ouverteAInscription, ouverteAuChoixDuCursus, titreAccesNecessaire, teleEnseignement, jamaisOuverteAInscription, jamaisOuverteAuChoixDuCursus, envoyeeAInscription, listeCalendrier, actualiserAdministrativement, tarification, codeTypeDiplome);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Formation {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    libelle: ").append(toIndentedString(libelle)).append("\n");
    sb.append("    libelleCourt: ").append(toIndentedString(libelleCourt)).append("\n");
    sb.append("    libelleLong: ").append(toIndentedString(libelleLong)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    periode: ").append(toIndentedString(periode)).append("\n");
    sb.append("    structureBudgetaire: ").append(toIndentedString(structureBudgetaire)).append("\n");
    sb.append("    listeCodeRegimeInscription: ").append(toIndentedString(listeCodeRegimeInscription)).append("\n");
    sb.append("    nbInscriptionsAutorisees: ").append(toIndentedString(nbInscriptionsAutorisees)).append("\n");
    sb.append("    listeCodeBourseEtAideFinanciere: ").append(toIndentedString(listeCodeBourseEtAideFinanciere)).append("\n");
    sb.append("    ouverteAInscription: ").append(toIndentedString(ouverteAInscription)).append("\n");
    sb.append("    ouverteAuChoixDuCursus: ").append(toIndentedString(ouverteAuChoixDuCursus)).append("\n");
    sb.append("    titreAccesNecessaire: ").append(toIndentedString(titreAccesNecessaire)).append("\n");
    sb.append("    teleEnseignement: ").append(toIndentedString(teleEnseignement)).append("\n");
    sb.append("    jamaisOuverteAInscription: ").append(toIndentedString(jamaisOuverteAInscription)).append("\n");
    sb.append("    jamaisOuverteAuChoixDuCursus: ").append(toIndentedString(jamaisOuverteAuChoixDuCursus)).append("\n");
    sb.append("    envoyeeAInscription: ").append(toIndentedString(envoyeeAInscription)).append("\n");
    sb.append("    listeCalendrier: ").append(toIndentedString(listeCalendrier)).append("\n");
    sb.append("    actualiserAdministrativement: ").append(toIndentedString(actualiserAdministrativement)).append("\n");
    sb.append("    tarification: ").append(toIndentedString(tarification)).append("\n");
    sb.append("    codeTypeDiplome: ").append(toIndentedString(codeTypeDiplome)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

