/*
 * REF v1 - Référentiel
 * Liste l'ensemble des services et des opérations disponibles dans le module Referentiel
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.esupportail.referentiel.pcscol.ref_api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;

import org.esupportail.referentiel.pcscol.invoker.ApiClient;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
/**
 * PersonnePresentation
 */
@JsonPropertyOrder({
  PersonnePresentation.JSON_PROPERTY_CODE_METIER,
  PersonnePresentation.JSON_PROPERTY_CIVILITE,
  PersonnePresentation.JSON_PROPERTY_SEXE,
  PersonnePresentation.JSON_PROPERTY_NOM_USAGE,
  PersonnePresentation.JSON_PROPERTY_NOM_FAMILLE,
  PersonnePresentation.JSON_PROPERTY_PRENOM1,
  PersonnePresentation.JSON_PROPERTY_PRENOM2,
  PersonnePresentation.JSON_PROPERTY_PRENOM3,
  PersonnePresentation.JSON_PROPERTY_DATE_NAISSANCE,
  PersonnePresentation.JSON_PROPERTY_DATE_DEBUT_VALIDITE,
  PersonnePresentation.JSON_PROPERTY_DATE_FIN_VALIDITE,
  PersonnePresentation.JSON_PROPERTY_PERSONNE_UTILISATEUR_LST,
  PersonnePresentation.JSON_PROPERTY_SOURCE_PERSONNE_LST,
  PersonnePresentation.JSON_PROPERTY_PERSONNE_TYPE_PERSONNE_LST
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-30T09:24:02.851634+02:00[Europe/Paris]", comments = "Generator version: 7.7.0")
public class PersonnePresentation {
  public static final String JSON_PROPERTY_CODE_METIER = "codeMetier";
  private String codeMetier;

  public static final String JSON_PROPERTY_CIVILITE = "civilite";
  private String civilite;

  public static final String JSON_PROPERTY_SEXE = "sexe";
  private String sexe;

  public static final String JSON_PROPERTY_NOM_USAGE = "nomUsage";
  private String nomUsage;

  public static final String JSON_PROPERTY_NOM_FAMILLE = "nomFamille";
  private String nomFamille;

  public static final String JSON_PROPERTY_PRENOM1 = "prenom1";
  private String prenom1;

  public static final String JSON_PROPERTY_PRENOM2 = "prenom2";
  private String prenom2;

  public static final String JSON_PROPERTY_PRENOM3 = "prenom3";
  private String prenom3;

  public static final String JSON_PROPERTY_DATE_NAISSANCE = "dateNaissance";
  private Date dateNaissance;

  public static final String JSON_PROPERTY_DATE_DEBUT_VALIDITE = "dateDebutValidite";
  private Date dateDebutValidite;

  public static final String JSON_PROPERTY_DATE_FIN_VALIDITE = "dateFinValidite";
  private Date dateFinValidite;

  public static final String JSON_PROPERTY_PERSONNE_UTILISATEUR_LST = "personneUtilisateurLst";
  private List<PersonneUtilisateur> personneUtilisateurLst = new ArrayList<>();

  public static final String JSON_PROPERTY_SOURCE_PERSONNE_LST = "sourcePersonneLst";
  private List<SourcePersonne> sourcePersonneLst = new ArrayList<>();

  public static final String JSON_PROPERTY_PERSONNE_TYPE_PERSONNE_LST = "personneTypePersonneLst";
  private List<PersonneTypePersonne> personneTypePersonneLst = new ArrayList<>();

  public PersonnePresentation() { 
  }

  public PersonnePresentation codeMetier(String codeMetier) {
    this.codeMetier = codeMetier;
    return this;
  }

  /**
   * Code métier de la personne &#x3D; PER + numéro
   * @return codeMetier
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE_METIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCodeMetier() {
    return codeMetier;
  }


  @JsonProperty(JSON_PROPERTY_CODE_METIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodeMetier(String codeMetier) {
    this.codeMetier = codeMetier;
  }


  public PersonnePresentation civilite(String civilite) {
    this.civilite = civilite;
    return this;
  }

  /**
   * Civilté de la personne
   * @return civilite
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CIVILITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCivilite() {
    return civilite;
  }


  @JsonProperty(JSON_PROPERTY_CIVILITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCivilite(String civilite) {
    this.civilite = civilite;
  }


  public PersonnePresentation sexe(String sexe) {
    this.sexe = sexe;
    return this;
  }

  /**
   * Sexe de la personne
   * @return sexe
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEXE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSexe() {
    return sexe;
  }


  @JsonProperty(JSON_PROPERTY_SEXE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSexe(String sexe) {
    this.sexe = sexe;
  }


  public PersonnePresentation nomUsage(String nomUsage) {
    this.nomUsage = nomUsage;
    return this;
  }

  /**
   * Nom d&#39;usage de la personne
   * @return nomUsage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOM_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNomUsage() {
    return nomUsage;
  }


  @JsonProperty(JSON_PROPERTY_NOM_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNomUsage(String nomUsage) {
    this.nomUsage = nomUsage;
  }


  public PersonnePresentation nomFamille(String nomFamille) {
    this.nomFamille = nomFamille;
    return this;
  }

  /**
   * Nom patronymique de la personne
   * @return nomFamille
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOM_FAMILLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNomFamille() {
    return nomFamille;
  }


  @JsonProperty(JSON_PROPERTY_NOM_FAMILLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNomFamille(String nomFamille) {
    this.nomFamille = nomFamille;
  }


  public PersonnePresentation prenom1(String prenom1) {
    this.prenom1 = prenom1;
    return this;
  }

  /**
   * Prénom principal de la personne
   * @return prenom1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRENOM1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPrenom1() {
    return prenom1;
  }


  @JsonProperty(JSON_PROPERTY_PRENOM1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrenom1(String prenom1) {
    this.prenom1 = prenom1;
  }


  public PersonnePresentation prenom2(String prenom2) {
    this.prenom2 = prenom2;
    return this;
  }

  /**
   * Prénom secondaire de la personne
   * @return prenom2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRENOM2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPrenom2() {
    return prenom2;
  }


  @JsonProperty(JSON_PROPERTY_PRENOM2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrenom2(String prenom2) {
    this.prenom2 = prenom2;
  }


  public PersonnePresentation prenom3(String prenom3) {
    this.prenom3 = prenom3;
    return this;
  }

  /**
   * Troisième prénom de la personne
   * @return prenom3
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRENOM3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPrenom3() {
    return prenom3;
  }


  @JsonProperty(JSON_PROPERTY_PRENOM3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrenom3(String prenom3) {
    this.prenom3 = prenom3;
  }


  public PersonnePresentation dateNaissance(Date dateNaissance) {
    this.dateNaissance = dateNaissance;
    return this;
  }

  /**
   * Date de naissance de la personne
   * @return dateNaissance
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_NAISSANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Date getDateNaissance() {
    return dateNaissance;
  }


  @JsonProperty(JSON_PROPERTY_DATE_NAISSANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateNaissance(Date dateNaissance) {
    this.dateNaissance = dateNaissance;
  }


  public PersonnePresentation dateDebutValidite(Date dateDebutValidite) {
    this.dateDebutValidite = dateDebutValidite;
    return this;
  }

  /**
   * Date du début de la validité de la personne
   * @return dateDebutValidite
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_DEBUT_VALIDITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Date getDateDebutValidite() {
    return dateDebutValidite;
  }


  @JsonProperty(JSON_PROPERTY_DATE_DEBUT_VALIDITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateDebutValidite(Date dateDebutValidite) {
    this.dateDebutValidite = dateDebutValidite;
  }


  public PersonnePresentation dateFinValidite(Date dateFinValidite) {
    this.dateFinValidite = dateFinValidite;
    return this;
  }

  /**
   * Date de la fin de la validité de la personne
   * @return dateFinValidite
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_FIN_VALIDITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Date getDateFinValidite() {
    return dateFinValidite;
  }


  @JsonProperty(JSON_PROPERTY_DATE_FIN_VALIDITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateFinValidite(Date dateFinValidite) {
    this.dateFinValidite = dateFinValidite;
  }


  public PersonnePresentation personneUtilisateurLst(List<PersonneUtilisateur> personneUtilisateurLst) {
    this.personneUtilisateurLst = personneUtilisateurLst;
    return this;
  }

  public PersonnePresentation addPersonneUtilisateurLstItem(PersonneUtilisateur personneUtilisateurLstItem) {
    if (this.personneUtilisateurLst == null) {
      this.personneUtilisateurLst = new ArrayList<>();
    }
    this.personneUtilisateurLst.add(personneUtilisateurLstItem);
    return this;
  }

  /**
   * Association entre personne et utilisateur
   * @return personneUtilisateurLst
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERSONNE_UTILISATEUR_LST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<PersonneUtilisateur> getPersonneUtilisateurLst() {
    return personneUtilisateurLst;
  }


  @JsonProperty(JSON_PROPERTY_PERSONNE_UTILISATEUR_LST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPersonneUtilisateurLst(List<PersonneUtilisateur> personneUtilisateurLst) {
    this.personneUtilisateurLst = personneUtilisateurLst;
  }


  public PersonnePresentation sourcePersonneLst(List<SourcePersonne> sourcePersonneLst) {
    this.sourcePersonneLst = sourcePersonneLst;
    return this;
  }

  public PersonnePresentation addSourcePersonneLstItem(SourcePersonne sourcePersonneLstItem) {
    if (this.sourcePersonneLst == null) {
      this.sourcePersonneLst = new ArrayList<>();
    }
    this.sourcePersonneLst.add(sourcePersonneLstItem);
    return this;
  }

  /**
   * Source d&#39;alimentation de personne (GRHUM, SINAPS, SIRH etablissement, ...)
   * @return sourcePersonneLst
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_PERSONNE_LST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SourcePersonne> getSourcePersonneLst() {
    return sourcePersonneLst;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_PERSONNE_LST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourcePersonneLst(List<SourcePersonne> sourcePersonneLst) {
    this.sourcePersonneLst = sourcePersonneLst;
  }


  public PersonnePresentation personneTypePersonneLst(List<PersonneTypePersonne> personneTypePersonneLst) {
    this.personneTypePersonneLst = personneTypePersonneLst;
    return this;
  }

  public PersonnePresentation addPersonneTypePersonneLstItem(PersonneTypePersonne personneTypePersonneLstItem) {
    if (this.personneTypePersonneLst == null) {
      this.personneTypePersonneLst = new ArrayList<>();
    }
    this.personneTypePersonneLst.add(personneTypePersonneLstItem);
    return this;
  }

  /**
   * Association entre personne et type personne
   * @return personneTypePersonneLst
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERSONNE_TYPE_PERSONNE_LST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<PersonneTypePersonne> getPersonneTypePersonneLst() {
    return personneTypePersonneLst;
  }


  @JsonProperty(JSON_PROPERTY_PERSONNE_TYPE_PERSONNE_LST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPersonneTypePersonneLst(List<PersonneTypePersonne> personneTypePersonneLst) {
    this.personneTypePersonneLst = personneTypePersonneLst;
  }


  /**
   * Return true if this PersonnePresentation object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonnePresentation personnePresentation = (PersonnePresentation) o;
    return Objects.equals(this.codeMetier, personnePresentation.codeMetier) &&
        Objects.equals(this.civilite, personnePresentation.civilite) &&
        Objects.equals(this.sexe, personnePresentation.sexe) &&
        Objects.equals(this.nomUsage, personnePresentation.nomUsage) &&
        Objects.equals(this.nomFamille, personnePresentation.nomFamille) &&
        Objects.equals(this.prenom1, personnePresentation.prenom1) &&
        Objects.equals(this.prenom2, personnePresentation.prenom2) &&
        Objects.equals(this.prenom3, personnePresentation.prenom3) &&
        Objects.equals(this.dateNaissance, personnePresentation.dateNaissance) &&
        Objects.equals(this.dateDebutValidite, personnePresentation.dateDebutValidite) &&
        Objects.equals(this.dateFinValidite, personnePresentation.dateFinValidite) &&
        Objects.equals(this.personneUtilisateurLst, personnePresentation.personneUtilisateurLst) &&
        Objects.equals(this.sourcePersonneLst, personnePresentation.sourcePersonneLst) &&
        Objects.equals(this.personneTypePersonneLst, personnePresentation.personneTypePersonneLst);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codeMetier, civilite, sexe, nomUsage, nomFamille, prenom1, prenom2, prenom3, dateNaissance, dateDebutValidite, dateFinValidite, personneUtilisateurLst, sourcePersonneLst, personneTypePersonneLst);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonnePresentation {\n");
    sb.append("    codeMetier: ").append(toIndentedString(codeMetier)).append("\n");
    sb.append("    civilite: ").append(toIndentedString(civilite)).append("\n");
    sb.append("    sexe: ").append(toIndentedString(sexe)).append("\n");
    sb.append("    nomUsage: ").append(toIndentedString(nomUsage)).append("\n");
    sb.append("    nomFamille: ").append(toIndentedString(nomFamille)).append("\n");
    sb.append("    prenom1: ").append(toIndentedString(prenom1)).append("\n");
    sb.append("    prenom2: ").append(toIndentedString(prenom2)).append("\n");
    sb.append("    prenom3: ").append(toIndentedString(prenom3)).append("\n");
    sb.append("    dateNaissance: ").append(toIndentedString(dateNaissance)).append("\n");
    sb.append("    dateDebutValidite: ").append(toIndentedString(dateDebutValidite)).append("\n");
    sb.append("    dateFinValidite: ").append(toIndentedString(dateFinValidite)).append("\n");
    sb.append("    personneUtilisateurLst: ").append(toIndentedString(personneUtilisateurLst)).append("\n");
    sb.append("    sourcePersonneLst: ").append(toIndentedString(sourcePersonneLst)).append("\n");
    sb.append("    personneTypePersonneLst: ").append(toIndentedString(personneTypePersonneLst)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `codeMetier` to the URL query string
    if (getCodeMetier() != null) {
      joiner.add(String.format("%scodeMetier%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCodeMetier()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `civilite` to the URL query string
    if (getCivilite() != null) {
      joiner.add(String.format("%scivilite%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCivilite()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `sexe` to the URL query string
    if (getSexe() != null) {
      joiner.add(String.format("%ssexe%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSexe()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `nomUsage` to the URL query string
    if (getNomUsage() != null) {
      joiner.add(String.format("%snomUsage%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getNomUsage()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `nomFamille` to the URL query string
    if (getNomFamille() != null) {
      joiner.add(String.format("%snomFamille%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getNomFamille()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `prenom1` to the URL query string
    if (getPrenom1() != null) {
      joiner.add(String.format("%sprenom1%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPrenom1()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `prenom2` to the URL query string
    if (getPrenom2() != null) {
      joiner.add(String.format("%sprenom2%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPrenom2()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `prenom3` to the URL query string
    if (getPrenom3() != null) {
      joiner.add(String.format("%sprenom3%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPrenom3()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `dateNaissance` to the URL query string
    if (getDateNaissance() != null) {
      joiner.add(String.format("%sdateNaissance%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDateNaissance()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `dateDebutValidite` to the URL query string
    if (getDateDebutValidite() != null) {
      joiner.add(String.format("%sdateDebutValidite%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDateDebutValidite()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `dateFinValidite` to the URL query string
    if (getDateFinValidite() != null) {
      joiner.add(String.format("%sdateFinValidite%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDateFinValidite()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `personneUtilisateurLst` to the URL query string
    if (getPersonneUtilisateurLst() != null) {
      for (int i = 0; i < getPersonneUtilisateurLst().size(); i++) {
        if (getPersonneUtilisateurLst().get(i) != null) {
          joiner.add(getPersonneUtilisateurLst().get(i).toUrlQueryString(String.format("%spersonneUtilisateurLst%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `sourcePersonneLst` to the URL query string
    if (getSourcePersonneLst() != null) {
      for (int i = 0; i < getSourcePersonneLst().size(); i++) {
        if (getSourcePersonneLst().get(i) != null) {
          joiner.add(getSourcePersonneLst().get(i).toUrlQueryString(String.format("%ssourcePersonneLst%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `personneTypePersonneLst` to the URL query string
    if (getPersonneTypePersonneLst() != null) {
      for (int i = 0; i < getPersonneTypePersonneLst().size(); i++) {
        if (getPersonneTypePersonneLst().get(i) != null) {
          joiner.add(getPersonneTypePersonneLst().get(i).toUrlQueryString(String.format("%spersonneTypePersonneLst%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

