/*
 * REF v1 - Référentiel
 * Liste l'ensemble des services et des opérations disponibles dans le module Referentiel
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.esupportail.referentiel.pcscol.ref_api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Objects;
import java.util.StringJoiner;

import org.esupportail.referentiel.pcscol.invoker.ApiClient;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
/**
 * StructureAvecUaiCreation
 */
@JsonPropertyOrder({
  StructureAvecUaiCreation.JSON_PROPERTY_CODE,
  StructureAvecUaiCreation.JSON_PROPERTY_CODE_UAI,
  StructureAvecUaiCreation.JSON_PROPERTY_CODE_REFERENTIEL_EXTERNE,
  StructureAvecUaiCreation.JSON_PROPERTY_TEMOIN_VISIBLE,
  StructureAvecUaiCreation.JSON_PROPERTY_COMMENTAIRE,
  StructureAvecUaiCreation.JSON_PROPERTY_RESPONSABLE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-30T09:24:02.851634+02:00[Europe/Paris]", comments = "Generator version: 7.7.0")
public class StructureAvecUaiCreation {
  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  public static final String JSON_PROPERTY_CODE_UAI = "codeUai";
  private String codeUai;

  public static final String JSON_PROPERTY_CODE_REFERENTIEL_EXTERNE = "codeReferentielExterne";
  private String codeReferentielExterne;

  public static final String JSON_PROPERTY_TEMOIN_VISIBLE = "temoinVisible";
  private Boolean temoinVisible;

  public static final String JSON_PROPERTY_COMMENTAIRE = "commentaire";
  private String commentaire;

  public static final String JSON_PROPERTY_RESPONSABLE = "responsable";
  private Responsable responsable;

  public StructureAvecUaiCreation() { 
  }

  public StructureAvecUaiCreation code(String code) {
    this.code = code;
    return this;
  }

  /**
   * Code Interne Pégase de l&#39;établissement (choisi par l&#39;établissement) - Clé fonctionnelle
   * @return code
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(String code) {
    this.code = code;
  }


  public StructureAvecUaiCreation codeUai(String codeUai) {
    this.codeUai = codeUai;
    return this;
  }

  /**
   * Code national de l&#39;établissement d&#39;enseignement supérieur, fourni par le ministère
   * @return codeUai
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE_UAI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCodeUai() {
    return codeUai;
  }


  @JsonProperty(JSON_PROPERTY_CODE_UAI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodeUai(String codeUai) {
    this.codeUai = codeUai;
  }


  public StructureAvecUaiCreation codeReferentielExterne(String codeReferentielExterne) {
    this.codeReferentielExterne = codeReferentielExterne;
    return this;
  }

  /**
   * id Référentiel Externe de pegase
   * @return codeReferentielExterne
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE_REFERENTIEL_EXTERNE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCodeReferentielExterne() {
    return codeReferentielExterne;
  }


  @JsonProperty(JSON_PROPERTY_CODE_REFERENTIEL_EXTERNE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodeReferentielExterne(String codeReferentielExterne) {
    this.codeReferentielExterne = codeReferentielExterne;
  }


  public StructureAvecUaiCreation temoinVisible(Boolean temoinVisible) {
    this.temoinVisible = temoinVisible;
    return this;
  }

  /**
   * Témoin de la visibilité
   * @return temoinVisible
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEMOIN_VISIBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getTemoinVisible() {
    return temoinVisible;
  }


  @JsonProperty(JSON_PROPERTY_TEMOIN_VISIBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemoinVisible(Boolean temoinVisible) {
    this.temoinVisible = temoinVisible;
  }


  public StructureAvecUaiCreation commentaire(String commentaire) {
    this.commentaire = commentaire;
    return this;
  }

  /**
   * Commentaire
   * @return commentaire
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENTAIRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCommentaire() {
    return commentaire;
  }


  @JsonProperty(JSON_PROPERTY_COMMENTAIRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommentaire(String commentaire) {
    this.commentaire = commentaire;
  }


  public StructureAvecUaiCreation responsable(Responsable responsable) {
    this.responsable = responsable;
    return this;
  }

  /**
   * Get responsable
   * @return responsable
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESPONSABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Responsable getResponsable() {
    return responsable;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponsable(Responsable responsable) {
    this.responsable = responsable;
  }


  /**
   * Return true if this StructureAvecUaiCreation object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StructureAvecUaiCreation structureAvecUaiCreation = (StructureAvecUaiCreation) o;
    return Objects.equals(this.code, structureAvecUaiCreation.code) &&
        Objects.equals(this.codeUai, structureAvecUaiCreation.codeUai) &&
        Objects.equals(this.codeReferentielExterne, structureAvecUaiCreation.codeReferentielExterne) &&
        Objects.equals(this.temoinVisible, structureAvecUaiCreation.temoinVisible) &&
        Objects.equals(this.commentaire, structureAvecUaiCreation.commentaire) &&
        Objects.equals(this.responsable, structureAvecUaiCreation.responsable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, codeUai, codeReferentielExterne, temoinVisible, commentaire, responsable);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StructureAvecUaiCreation {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    codeUai: ").append(toIndentedString(codeUai)).append("\n");
    sb.append("    codeReferentielExterne: ").append(toIndentedString(codeReferentielExterne)).append("\n");
    sb.append("    temoinVisible: ").append(toIndentedString(temoinVisible)).append("\n");
    sb.append("    commentaire: ").append(toIndentedString(commentaire)).append("\n");
    sb.append("    responsable: ").append(toIndentedString(responsable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `code` to the URL query string
    if (getCode() != null) {
      joiner.add(String.format("%scode%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `codeUai` to the URL query string
    if (getCodeUai() != null) {
      joiner.add(String.format("%scodeUai%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCodeUai()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `codeReferentielExterne` to the URL query string
    if (getCodeReferentielExterne() != null) {
      joiner.add(String.format("%scodeReferentielExterne%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCodeReferentielExterne()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `temoinVisible` to the URL query string
    if (getTemoinVisible() != null) {
      joiner.add(String.format("%stemoinVisible%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTemoinVisible()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `commentaire` to the URL query string
    if (getCommentaire() != null) {
      joiner.add(String.format("%scommentaire%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCommentaire()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `responsable` to the URL query string
    if (getResponsable() != null) {
      joiner.add(getResponsable().toUrlQueryString(prefix + "responsable" + suffix));
    }

    return joiner.toString();
  }
}

